apiVersion: v1
kind: ConfigMap
metadata:
  name: vdb-config
  namespace: vdb-system
  labels:
    app.kubernetes.io/name: cuda-vector-db
    app.kubernetes.io/component: config
data:
  production.yaml: |
    server:
      address: "0.0.0.0:50051"
      max_batch_size: 64
      coalesce_window_ms: 2
      max_concurrent_searches: 32
      gpu_memory_limit_gb: 8
      enable_multi_gpu: true
      data_path: "/data/vdb"
      epochs_path: "/data/epochs"
      indices_path: "/data/indices"
      thread_pools:
        search_workers: 8
        admin_workers: 4
        io_workers: 4
      circuit_breaker:
        error_threshold: 0.5
        timeout_ms: 30000
        recovery_timeout_ms: 60000
      rate_limit:
        requests_per_second: 10000
        burst_size: 200
    monitoring:
      metrics_port: 8080
      metrics_path: "/metrics"
      health_check_interval_ms: 5000
      log_level: "INFO"
      log_format: "json"
      log_file: "/var/log/vdb/server.log"
      enable_tracing: false
    cuda:
      device_memory_pool_size_gb: 4
      pinned_memory_pool_size_gb: 1
      num_streams: 8
      stream_priorities: true
      strict_error_checking: true
      memory_validation: true
    indexes:
      default_nlist: 256
      default_nprobe: 32
      default_metric: "L2"
      list_cache_size_gb: 2
      prefetch_ratio: 0.3
      auto_compact: true
      compact_threshold: 0.7
    security:
      enable_tls: false
      enable_auth: false