apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vdb-server
  namespace: vdb-system
  labels:
    app.kubernetes.io/name: cuda-vector-db
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cuda-vector-db
      app.kubernetes.io/component: server
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod_name
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node_name
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: kubernetes_namespace
    metricRelabelings:
    # Keep only VDB metrics
    - sourceLabels: [__name__]
      regex: vdb_.*
      action: keep